version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands: ["npm install"]
        build:
          commands: ["npm run build:app"]
      artifacts:
        baseDirectory: app/dist
        files:
          - "**/*"
      cache:
        paths:
          - "node_modules/**/*"
      buildPath: /
    appRoot: app
