name: "Chromatic"

on:
  push:
    branches: [main]
    paths:
      - "ui/**"
  pull_request:
    branches: [main]
    paths:
      - "ui/**"

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Rebuild native modules (lefthook fix)
        run: npm rebuild

      - name: Publish to Chromatic
        working-directory: ./ui
        run: npm run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
